[package]
name = "taisenkai"
version = "0.1.0"
authors = ["Johan Gall <johan.gall@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33"
actix-web = "~1.0"
diesel = "~1.4"
file = "~1.1"
